name: notes_app
description: "Notes App 1"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  test: ^1.25.7
  mockito: ^5.4.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_ui_auth: ^1.12.0
  cloud_firestore: ^4.13.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth_platform_interface: ^7.0.9
flutter:
  uses-material-design: true